import { Channel } from "@/types/tv";

export const NOSTALGICT_ADS_PLAYLIST_ID = "PLycor1XF7S9HVMnWxndl27HgZJM5S8wRT";

export const CHANNELS: Channel[] = [
  // ==========================================
  // CATEGORY 1: 📺 VINTAGE 80s/90s ADS (CH 01 - 10)
  // ==========================================
  {
    id: "maggi-90s",
    channelNumber: 1,
    title: "2 Minute Noodles - Mummy Bhook Lagi",
    brand: "Maggi",
    year: "1993",
    youtubeIds: ["jiWoiNog4gQ", "wpj2qkaE7YQ", "7I5OvEzLG6I"],
    category: "Commercials",
    description: "The iconic 2-minute noodles ad that defined school break time in 90s India.",
  },
  {
    id: "bajaj-chetak",
    channelNumber: 2,
    title: "Buland Bharat Ki Buland Tasveer",
    brand: "Hamara Bajaj",
    year: "1989",
    youtubeIds: ["scltYH13uEY", "ZAB0zmUA54g", "CMY218EiA6U"],
    category: "Commercials",
    description: "Hamara Bajaj Chetak - an emotional anthem of middle-class Indian aspirations.",
  },
  {
    id: "nirma-powder",
    channelNumber: 3,
    title: "Doodh Si Safedi Nirma Se Aaye",
    brand: "Washing Powder Nirma",
    year: "1987",
    youtubeIds: ["wpj2qkaE7YQ", "jiWoiNog4gQ", "xNWWBEXXtLE"],
    category: "Commercials",
    description: "Jaya, Sushma, Karishma aur Jaya... Sabki pasand Nirma!",
  },
  {
    id: "cadbury-dairy-milk",
    channelNumber: 4,
    title: "Asli Swad Zindagi Ka (Cricket Dance)",
    brand: "Cadbury Dairy Milk",
    year: "1994",
    youtubeIds: ["e7JATezA1nY", "ZAB0zmUA54g", "7I5OvEzLG6I"],
    category: "Commercials",
    description: "Shimona Rashi dancing on the cricket field after a match-winning six.",
  },
  {
    id: "vicco-vajradanti",
    channelNumber: 5,
    title: "Ayurvedic Jadibutiyo Se Nirmit",
    brand: "Vicco Vajradanti",
    year: "1985",
    youtubeIds: ["q88-eayDTrk", "CMY218EiA6U", "scltYH13uEY"],
    category: "Commercials",
    description: "Vicco Vajradanti ayurvedic paste and powder classic Doordarshan jingle.",
  },
  {
    id: "dhara-jalebi",
    channelNumber: 6,
    title: "Jalebi! - Remained Iconic Forever",
    brand: "Dhara Refined Oil",
    year: "1996",
    youtubeIds: ["7I5OvEzLG6I", "jiWoiNog4gQ", "ax5Fl7huJZw"],
    category: "Commercials",
    description: "Child running away from home until he hears Mummy is making hot crispy Jalebis!",
  },
  {
    id: "action-shoes",
    channelNumber: 7,
    title: "O Ho Ho School Time! Action Time!",
    brand: "Action School Shoes",
    year: "1995",
    youtubeIds: ["ax5Fl7huJZw", "e7JATezA1nY", "wpj2qkaE7YQ"],
    category: "Commercials",
    description: "The energetic morning routine song every Indian kid sang before boarding the school bus.",
  },
  {
    id: "pepsi-dil-maange-more",
    channelNumber: 8,
    title: "Yeh Dil Maange More!",
    brand: "Pepsi India",
    year: "1998",
    youtubeIds: ["ZAB0zmUA54g", "e7JATezA1nY", "fZqa4OtUlGY"],
    category: "Commercials",
    description: "Shah Rukh Khan, Sachin Tendulkar, and Rani Mukerji in the peak 90s Pepsi era.",
  },
  {
    id: "doordarshan-title",
    channelNumber: 9,
    title: "Original Doordarshan Montage & Tune",
    brand: "Doordarshan DD National",
    year: "1995",
    youtubeIds: ["CMY218EiA6U", "scltYH13uEY", "q88-eayDTrk"],
    category: "Commercials",
    description: "The iconic spinning peacock logo and nostalgic opening whistle tune of DD National.",
  },
  {
    id: "amul-taste-of-india",
    channelNumber: 10,
    title: "The Taste of India Anthem",
    brand: "Amul",
    year: "1997",
    youtubeIds: ["xNWWBEXXtLE", "jiWoiNog4gQ", "7I5OvEzLG6I"],
    category: "Commercials",
    description: "An evocative visual journey through rural and urban India unified by Amul.",
  },

  // ==========================================
  // CATEGORY 2: 🏹 MAHABHARAT (B.R. CHOPRA CLASSIC) (CH 11 - 15)
  // ==========================================
  {
    id: "mahabharat-full-series",
    channelNumber: 11,
    title: "B.R. Chopra Mahabharat Full Series Stream",
    brand: "Mahabharat Full Series",
    year: "1988",
    playlistId: "PLa6CHPhFNfadNcnVZRXa6csHL5sFdkwmV",
    category: "Mahabharat",
    description: "Complete 94-episode epic saga of B.R. Chopra's Mahabharat broadcast on Doordarshan.",
  },
  {
    id: "mahabharat-ep1",
    channelNumber: 12,
    title: "Episode 01 - King Shantanu & Ganga (Arambh)",
    brand: "Mahabharat Ep 01",
    year: "1988",
    youtubeIds: ["TltC-AllzGY", "AkcXCFlEqqk", "es4QFIh3m8w"],
    category: "Mahabharat",
    description: "The beginning of Kuru Dynasty - Samay Speaks and the legend of Shantanu & Ganga.",
  },
  {
    id: "mahabharat-geeta-saar",
    channelNumber: 13,
    title: "Shri Krishna Bhagavad Gita Updesh (Geeta Saar)",
    brand: "Mahabharat Gita Saar",
    year: "1989",
    youtubeIds: ["AkcXCFlEqqk", "es4QFIh3m8w", "TltC-AllzGY"],
    category: "Mahabharat",
    description: "Lord Krishna imparts the sacred philosophy of Bhagavad Gita to Arjuna at Kurukshetra.",
  },
  {
    id: "mahabharat-vastraharan",
    channelNumber: 14,
    title: "Draupadi Vastraharan Iconic Scene",
    brand: "Mahabharat Classic",
    year: "1989",
    youtubeIds: ["es4QFIh3m8w", "AkcXCFlEqqk", "TltC-AllzGY"],
    category: "Mahabharat",
    description: "The pivotal turning point of Mahabharat - Lord Krishna protects Draupadi's honor.",
  },
  {
    id: "mahabharat-alt-playlist",
    channelNumber: 15,
    title: "Mahabharat Complete Archive Playlist",
    brand: "Mahabharat Archive",
    year: "1988",
    playlistId: "PLxs1iWrwyHgWLMx0yjVziA1Y-cRFkRdIE",
    category: "Mahabharat",
    description: "Organized complete episode collection with English subtitles.",
  },

  // ==========================================
  // CATEGORY 3: 🕉️ RAMAYAN (RAMANAND SAGAR CLASSIC) (CH 16 - 20)
  // ==========================================
  {
    id: "ramayan-full-series",
    channelNumber: 16,
    title: "Ramanand Sagar Ramayan Full Series Stream",
    brand: "Ramayan Full Series",
    year: "1987",
    playlistId: "PLFPJRCFRDARSZofcQcV6m7Pu2EAL8_1dv",
    category: "Ramayan",
    description: "The world-famous serial that brought India to a standstill every Sunday morning on Doordarshan.",
  },
  {
    id: "ramayan-ep1",
    channelNumber: 17,
    title: "Episode 01 - King Dasharath Yajna & Shri Ram Janm",
    brand: "Ramayan Ep 01",
    year: "1987",
    youtubeIds: ["vIh99bkSc_w", "NisfIUglozc"],
    category: "Ramayan",
    description: "Putrakameshthi Yajna by Sage Rishyasringa and the divine birth of Shri Ram in Ayodhya.",
  },
  {
    id: "ramayan-sita-swayamvar",
    channelNumber: 18,
    title: "Sita Swayamvar & Shiv Dhanush Bhang",
    brand: "Ramayan Classic",
    year: "1987",
    youtubeIds: ["NisfIUglozc", "vIh99bkSc_w"],
    category: "Ramayan",
    description: "Shri Ram lifts and breaks Lord Shiva's bow in Janakpuri to marry Devi Sita.",
  },
  {
    id: "ramayan-tilak-playlist",
    channelNumber: 19,
    title: "Ramayan HD Widescreen Remastered Series",
    brand: "Ramayan Remastered",
    year: "1987",
    playlistId: "PLf4G4AIPelQvfrhdaC7ogl_iDklvjhWyj",
    category: "Ramayan",
    description: "Tilak Channel official remastered Ramayan broadcast collection.",
  },
  {
    id: "ramayan-uttar-playlist",
    channelNumber: 20,
    title: "Uttar Ramayan & Luv Kush Katha",
    brand: "Uttar Ramayan",
    year: "1989",
    playlistId: "PLNK99YCwQjpcvFUXSY898Yq9BqMY9X1PA",
    category: "Ramayan",
    description: "The legendary continuation featuring Luv & Kush singing Ramayana in Shri Ram's court.",
  },

  // ==========================================
  // CATEGORY 4: 🏏 VINTAGE INDIAN CRICKET MATCHES (CH 21 - 25)
  // ==========================================
  {
    id: "cricket-1998-sharjah",
    channelNumber: 21,
    title: "1998 Sharjah Desert Storm - Sachin Tendulkar 143 vs Australia",
    brand: "Sharjah 1998",
    year: "1998",
    youtubeIds: ["fZqa4OtUlGY", "BxduHWaPtoc", "awJKGhcGCCc"],
    category: "Cricket",
    description: "Sachin's legendary sandstorm masterpiece in Sharjah against Warne & McGrath.",
  },
  {
    id: "cricket-1996-ind-pak",
    channelNumber: 22,
    title: "1996 World Cup QF - Prasad vs Aamir Sohail Off-Stump Revenge",
    brand: "World Cup 96",
    year: "1996",
    youtubeIds: ["BxduHWaPtoc", "fZqa4OtUlGY", "awJKGhcGCCc"],
    category: "Cricket",
    description: "Venkatesh Prasad clean bowls Aamir Sohail right after getting taunted in Bangalore.",
  },
  {
    id: "cricket-2001-eden-gardens",
    channelNumber: 23,
    title: "2001 Eden Gardens Test - VVS Laxman 281 & Dravid Comeback",
    brand: "Eden Gardens 01",
    year: "2001",
    youtubeIds: ["awJKGhcGCCc", "fZqa4OtUlGY", "BxduHWaPtoc"],
    category: "Cricket",
    description: "India's greatest Test victory following-on against Steve Waugh's invincible Australians.",
  },
  {
    id: "cricket-90s-playlist",
    channelNumber: 24,
    title: "Classic 90s Indian Cricket Matches & Highlights",
    brand: "Cricket 90s Archive",
    year: "1995",
    youtubeIds: ["BxduHWaPtoc", "awJKGhcGCCc", "fZqa4OtUlGY"],
    category: "Cricket",
    description: "Classic highlights from 90s ODI series, Hero Cup, and Sharjah tournaments.",
  },
  {
    id: "cricket-nostalgia-special",
    channelNumber: 25,
    title: "Best of Vintage Indian Cricket Moments",
    brand: "Cricket Vintage",
    year: "1983",
    youtubeIds: ["fZqa4OtUlGY", "BxduHWaPtoc", "awJKGhcGCCc"],
    category: "Cricket",
    description: "Iconic catches, last-over finishes, and unforgettable Indian cricket victories.",
  },
];



